# fly.toml app configuration file generated for ourstory on 2024-08-19T19:42:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ourstory'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1.5gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  VITE_APP_NODE_ENV = 'production'