name: Auto deploy to Fly
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy client
        run: |
          cd client
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN_OURSTORY_FRONTEND }}
      - name : Deploy server
        run: | 
          cd server
          flyctl deploy --remote-only 
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN_OURSTORY_API }}


