name: Auto deploy to Fly
on:
  push:
    branches:
      - Fix_super_fly_command_typo
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Change directory 
        run: cd client
      - name: Deploy client to fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN_OURSTORY_FRONTEND }}
